dist: trusty
sudo: required
language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore ./MySolution/MySolution.sln
  - dotnet test ./MySolution/MyNetStandard.Tests/MyNetStandard.Tests.csproj
